### ISSUE TITLE
Wirecard signature flow

### ISSUE THREAD

**Issue by divyanshyadav** [mposSVK/acceptSDK#10]
Hello,
I have to ask a question about signature flow.
1. When do following callback functions will call during the flow?
   i). void (^signatureVerification)(AcceptTransaction_, AcceptSignatureVerificationResultCallback,NSError_)
   ii).  void(^signature)(AcceptSignatureRequest \* )

**Comment by WirecardMobileServices** [comment]
In the case the CVM states the Signature to be collected then:
1. signature callback is executed - you should use it to display the Signature capture screen - design it the way you like and capture the customers signature as UIImage
1.1 Use the AcceptSignatureRequest from the signature callback to post the signature back to the SDK
2. If the signature was collected during the payment flow (based on CVM) then the signatureVerification callback is executed at the end for the Merchant to confirm that the collected signature matches that on the Customers card. The result of visual signature comparison is then posted back to SDK by executing AcceptSignatureVerificationResultCallback with AcceptSignatureVerificationResultApproved or AcceptSignatureVerificationResultRejected

For the implementation details see the Demo application

**Comment by divyanshyadav** [comment]
After sending Image back to SDK, Call comes back to AcceptSignatureVerificationResultCallback but in it signatureVerificationCallbackMerchantResponse is coming NULL so it executes the else statement and then after some time terminal ask for signature verification. After pressing OK on terminal then call comes to (^completion)(AcceptTransaction_, NSError_)

So, Is there any way to stop the flow until user confirms it from the terminal.

**Comment by WirecardMobileServices** [comment]
That is expected behaviour as SPm2 terminal is capable of presenting the UI for confirming the signature verification dialogue.
Forgot to mention that AcceptSignatureVerificationResultCallback is NOT nil only for the terminals without the display - in which case the signature verification must be done on the app side.

In the case of SPm2 - the signature verification is done on the terminal by pressing O or X

**Comment by divyanshyadav** [comment]
Thanks for the reply, I have one another question. Are we able to accelerate the signature verification as it takes around 10 sec to appear "signature verification question" on terminal.

**Comment by WirecardMobileServices** [comment]
Once the message "Please give this device to the attendant" appears on the terminal, pressing the green (circle) button will prompt "Is cardholder signature OK?" in zero seconds instead of ten. Is that what you were asking for?

**Comment by divyanshyadav** [comment]
Thanks for solution.
