### ISSUE TITLE
Wirecard Login Failed

### ISSUE THREAD

**Issue by divyanshyadav** [mposSVK/acceptSDK#13]
This is the error message.

Error Domain=AcceptCommonErrorCode Code=2 "The operation couldn’t be completed. (AcceptCommonErrorCode error 2.)" UserInfo={
    NSUnderlyingError = "Error Domain=HTTP Code=-1012 \"Client/Server certificate mismatch\" UserInfo={\n    NSLocalizedDescription = \"Client/Server certificate mismatch\";\n}";
}

Could you please tell the root cause of this error?

**Comment by divyanshyadav** [comment]
Facing same issue in acceptSDK demo also.

**Comment by schwindt** [comment]
same problem here since yesterday

**Comment by RadoslavDanko** [comment]
The certificates were regenerated on the sdk-integration dev server. Please use the latest 1.6.192 acceptSDK

**Comment by schwindt** [comment]
ok it works with the latest SDK version. Luckily we had no app with this sdk version in the app store.

**Comment by RadoslavDanko** [comment]
Hi, you shouldn't have the app pointing to that environment in the app store in any case.
This environment is for development purposes only.
For the production you would receive different configuration or connection details.

**Comment by schwindt** [comment]
so you mean the self.backendConfig.url (we will change for the release) will not have this problem with certificates?

**Comment by RadoslavDanko** [comment]
The certificate issue you experiences is linked to the SDK public key pinning functionality - as the certificate was changed on the development server prior to the SDK release we encountered this issue. 

In production environment you will get information about upcoming certificate refresh at least 4 weeks in advance and both old and new public key will be validated by SDK for the transition period

**Comment by schwindt** [comment]
ok. thx for this information.
