### ISSUE TITLE
App crashes if one of config param is missed

### ISSUE THREAD

**Issue by 34xi** [mposSVK/acceptSDK#14]
Hello,

The app crashes if AcceptDataServiceConfig not filled completely and requestAccessToken is called.

it would be nice if lib return some more clear error in that case instead of crash. 
Something like: 

> AcceptDataServiceConfig.{field_name} did not set.

AcceptDataServiceConfig *config = [AcceptDataServiceConfig new];
// If one of lines bellow is skipped app crashes:
config.url = @"http://example.com";
config.callbackUrl = @"http://example.com";
config.clientId = @"clientId";
config.clientSecret = @"secret";

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
> **\* First throw call stack:
> (
>     0   CoreFoundation                      0x000000010e8f3d85 __exceptionPreprocess + 165
>     1   libobjc.A.dylib                     0x000000010defddeb objc_exception_throw + 48
>     2   CoreFoundation                      0x000000010e7f023e -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 318
>     3   CoreFoundation                      0x000000010e8025bb +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
>     4   icd                                 0x000000010c48d2ac -[AcceptDataService requestAccessToken:password:error:] + 368
>     5   icd                                 0x000000010c47a669 __56-[Accept requestAccessToken:password:config:completion:]_block_invoke + 157

**Comment by WirecardMobileServices** [comment]
Are you still encountering the issue ?

**Comment by 34xi** [comment]
Hi, did not checked yet, because I am using my own wrapper that check every passed arguments and return appropriate error objects for all of them.
