### ISSUE TITLE
Successful payment using invalid VISA card in AcceptSDK demo

### ISSUE THREAD

**Issue by divyanshyadav** [mposSVK/acceptSDK#17]
According to the code provided in accept SDK demo for payment completion

```
    void (^completion)(AcceptTransaction*, NSError*) = ^(AcceptTransaction *transaction, NSError *error)
    {
        if (error || !transaction)
        {
            [weakSelf paymentFailure:error transaction:transaction];
        }
        else
        {
            [weakSelf performSelectorOnMainThread:@selector(paymentDone:) withObject:transaction waitUntilDone:NO];
        }
    };

```
paymentFailure: will only called if there is an error or transaction object is null.

But when I have done transaction using invalid visa card, it called paymentDone: method, after that I have debugged it and found out that there was not error object but there is transaction object with status 'rejected' (means else condition will execute) which leads to payment success.

So my questing it where should I put the constraint to check if the payment is successful or not by using transaction object itself.
Or when the transaction object is not null.

**Comment by WirecardMobileServices** [comment]
On payment completion the paymentFailure is called if error or no transaction data immediately, however then the "paymentDone" is called which has further checks for the transaction approval.

` if ([transaction.state isEqualToString:@"approved"] || [transaction.state isEqualToString:@"authorized"])`

It would have been cleaner in the demo just to call paymentDone and put the error || !transaction together with "status" check in one place - will update the demo app later

However the "paymentDone" should not be confused with "Transaction approved" in any case

**Comment by divyanshyadav** [comment]
Ok. Thanks for the answer. We will put up a check there as well.
