### ISSUE TITLE
AppStore submit error caused by CFBundleExecutable key in info.plist

### ISSUE THREAD

**Issue by schwindt** [mposSVK/acceptSDK#19]
During the AppStore submit we got the following error message from Apple:

"Unexpected CFBundleExecutable Key. The bundle at 'Payload/EasyEntry.app/acceptResources.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

Should we just remove the CFBundleExecutable key from the acceptResources.bundle/info.plist?

**Comment by WirecardMobileServices** [comment]
Yes it should be sufficient. It looks like during the SDK build the Xcode added this key even though the CFBundlePackageType was set to BNDL

**Comment by schwindt** [comment]
ok, I will try without. Thx for the fast reply.

**Comment by schwindt** [comment]
Apple accepted the build version without the CFBundleExecutable key. Thx

**Comment by WirecardMobileServices** [comment]
Excellent
