### ISSUE TITLE
Reconnect posmate device after restart 

### ISSUE THREAD

**Issue by v3yr0n** [mposSVK/acceptSDK#2]
Hi!
I have a question: I'm running the ios app on my device, then i get the posmate via bluetooth. If i do a payment without disconnecting postmate it works well, but if i restart postmate i'm not able to do the payment... So, how can I detect if the device was disconnected and reconnect it again? 

Thanks!

**Comment by WirecardMobileServices** [comment]
Hi,

I presume you are using the demo application. 
Check the phone settings > Bluetooth and confirm the terminal is Connected
The Demo application has the terminal selector on the Payment screen - if you select the Vendor Terminal from the dropdown and perform the payment it should work if the terminal is connected.

Bear in mind that if the Bluetooth connection is closed, or terminal switched off, the Terminal selector is not being refreshed in the Demo application.
So you might be seeing the previously selected terminal by its S/N however the terminal might be off.

Also after restarting the terminal it can take a minute or so till the terminal is in the "Ready" mode and capable of accepting the communication.

Can you therefore check:
- terminal display shows "Next customer" or "Ready"
- phone settings -> Bluetooth show "Connected" for the selected terminal S/N
- terminal is selected in the dropdown 

![terminal ready](https://cloud.githubusercontent.com/assets/12099694/9545832/a37fd202-4d8d-11e5-893c-db8ec4d2d4b1.png)

![terminal bluetooth connected](https://cloud.githubusercontent.com/assets/12099694/9545782/37034abe-4d8d-11e5-89e9-fe5ac7290163.PNG)
![terminal selected](https://cloud.githubusercontent.com/assets/12099694/9545803/5cdebd90-4d8d-11e5-8ced-8a9ad01c818a.PNG)

**Comment by v3yr0n** [comment]
Hi!
No, i'm not using the demo application. 
But basically what happens is, I pass in a connection screen (that does the connection with the posmate) and then a go to a screen where i input the amount to pay. If i restart posmate, when i try to pay i have the "EAAccessory disconneced" error. 
So, my question is, how can I "refresh" the devices and use the newly connected one? 

And BTW, is there any way i can check if postmate got disconnected?

**Comment by WirecardMobileServices** [comment]
Hi,
Sorry for the late response - had a few days off.

Well "EAAccessory disconnected" means the bluetooth connection with the terminal was dropped.
The Posmate extension implements EAAccessoryDelegate accessoryDidDisconnect method and if in the payment flow then you would get the error message with the EAAccessory disconnected detail to which you should react (E.g. prompt the user to check the BT connection, or the terminal battery level etc)

The flow should be:
1. discover available terminals (call discoverSupportedVendors and discoverTerminalsForVendor to get available terminal list)
2. choose the one you would like to use for the transaction and remember Vendor UUID and Terminal UUID
3. call startPay method from the SDK using the proper combination of vendor UUID and Terminal UUID

I suggest you refer to the example application and integration guide (Integration Guide Accept SDK.pdf) which are bundled with the SDK and have a look at the startPay and discover... methods

If you want to check for the terminal connection upfront then you need to register for EAAccessoryDidDisconnectNotification and EAAccessoryDidConnectNotification notifications and implement your custom methods to save the terminal connection status somewhere in the class variable e.g. "isTerminalConnected" - then check that class variable prior to calling startPay method

**Comment by WirecardMobileServices** [comment]
No more issues reported after the advice
