### ISSUE TITLE
cancelPaymentFlow not working

### ISSUE THREAD

**Issue by moorthysubu** [mposSVK/acceptSDK#20]
Hey.I have started payment flow by AcceptSDK.startPayment(); & startPaymentFlow() with Thyron Extension but once the payment flow in progress i cannot able to cancel the payment flow the spm2 device still shows progress even i have called cancelPaymentFlow(); method as per doc. Can anyone please give me clarification on this.and how can i cancel payment process

**Comment by staskus** [comment]
Hey,

Having same issue.

Is there any why to bypass this issue or is it only possible to cancel the payment flow only with some specific payment methods? 

Thanks.

**Comment by FranciscoFortes** [comment]
Hi nitesuit, please write the comment (if not already existing) in the Android project.
https://github.com/mposSVK/acceptSDK-Android
You wrote the issue in the iOS one.

**Comment by staskus** [comment]
Hi,

I wrote the issue in iOS project because I have the problem on iOS.

**Comment by FranciscoFortes** [comment]
Hi nitesuit,

cancelPay only works when the system expects interaction, but not on the terminal itself. That means:
a) If the terminal is requesting user to do something (it prompts for inserting card or pressing buttons), then the terminal is listening to its own interface only, not the SDK. The hardware is designed that way.
b) And if the SDK is waiting for some online response or result, obviously nothing can be stopped/cancelled until the response or result arrives.

As defined in the documentation:

/**
* @brief Cancel the payment flow. This is usually called from UI (cancel button when
available) or some error from signature or completion block. Notice that an improper usage of this function (for example during online communication or level 2 flow in terminal) can produce unexpected errors
**/
- (void) cancelPay;

So, cancelPay is called automatically when the terminal allows you to press the button "X" or some online error happens, but it is also exposed in the SDK for you to use it in cases such as signature input. Most phases of the payment flow are active and cannot be externally stop anytime.

**Comment by staskus** [comment]
Thanks for the answer!
