### ISSUE TITLE
two equal eaaSerialNumber from discoverTerminalsForVendor method

### ISSUE THREAD

**Issue by schwindt** [mposSVK/acceptSDK#21]
Hi guys,

when I have two Spire SPm2 devices connected to my iPhone and then I call this method here:
```
- (void) discoverTerminalsForVendor:(NSString*)vendorUUID
                         completion:(void (^)(NSArray *, NSError*))completionBlock;
```

I get two AcceptTerminal objects with different uuid, displayName and alternativeDisplayName, but the eaaSerialNumber are the same for both.

After this, I call the 

```
- (void) startPay:(AcceptPaymentConfig*)config
       completion:(void (^)(AcceptTransaction*, NSError*))completion
         progress:(void (^)(AcceptStateUpdate))progress
        signature:(void (^)(AcceptSignatureRequest*))signatureRequest
signatureVerification:(void (^)(AcceptTransaction*,AcceptSignatureVerificationResultCallback , NSError*))signatureVerification
     appSelection:(void (^)(AcceptAppSelectionRequest *))appSelection;
```

Method with the eaaSerialNumber inside of the config variable. Cause for both devices they are the same, it will be always one device triggered as payment device. So my device selection before is useless, because its always the same device.

Is there a problem with the SDK or is there something I am doing wrong?

**Comment by WirecardMobileServices** [comment]
Hi,

yep, our problem with BT serialNumber being the same for more than one terminal of the same type paired.
Can you check 1.6.200 in which we use terminal name as advertised by the device - this is unique, so should not have the issue with addressing the device correctly.

Rado.

**Comment by schwindt** [comment]
Yes, now it works fine. Thx!

**Comment by WirecardMobileServices** [comment]
Cheers for confirmation
