### ISSUE TITLE
Getting payment status as INCOMPLETE in onPaymentSuccessful()

### ISSUE THREAD

**Issue by moorthysubu** [mposSVK/acceptSDK#23]
Hey,

When try to make a transaction its getting completed successfully and its triggers `onPaymentSuccessful()` method with `payment `object. but when I try to get the status of the transactions from the payment object its always gives the response as the 
`"status":"INCOMPLETE",`. but when i access the same transactions from the payment history it has a status as  "APPROVED". can you tell me when this status will change incomplete to complete or approved?

accept sdk version : 1.5.7
android-extension-spire:1.5.5

Thanks

**Comment by WirecardMobileServices** [comment]
Can you open please in acceptSDK-Android

**Comment by moorthysubu** [comment]
Sure! Thanks.
