### ISSUE TITLE
Please look into the issue

### ISSUE THREAD

**Issue by divyanshyadav** [mposSVK/acceptSDK#29]
Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x184df2d8c __exceptionPreprocess
1  libobjc.A.dylib                0x183fac5ec objc_exception_throw
2  CoreFoundation                 0x184e00098 __methodDescriptionForSelector
3  CoreFoundation                 0x184df85c8 ___forwarding___
4  CoreFoundation                 0x184cde41c _CF_forwarding_prep_0
5  INFINIA_PRODUCTION_TARGET      0x104cb77c4 +[AcceptDeserialization safeString:key:] (AcceptDeserialization.m:115)
6  INFINIA_PRODUCTION_TARGET      0x104cb670c +[AcceptTransactionDeserialization deserialize:] (AcceptTransactionDeserialization.m:154)
7  INFINIA_PRODUCTION_TARGET      0x104c8b39c -[AcceptDataService requestNewPayment:accessToken:signature:terminalInfo:basket:cardInfo:extendedInfo:error:] (AcceptDataService.m:708)
8  INFINIA_PRODUCTION_TARGET      0x104c77700 __84-[Accept startPay:completion:progress:signature:signatureVerification:appSelection:]_block_invoke.1066 (Accept.m:2273)
9  INFINIA_PRODUCTION_TARGET      0x104ceac7c __123-[PosMateExtension startPay:completion:progress:onlineProcessor:configuration:signature:appSelection:updateSignatureForCL:]_block_invoke_2.354 (PosMateExtension.m:540)
10 libdispatch.dylib              0x1846e4b24 _dispatch_call_block_and_release
11 libdispatch.dylib              0x1846e4ae4 _dispatch_client_callout
12 libdispatch.dylib              0x1846ebc08 _dispatch_queue_override_invoke$VARIANT$mp
13 libdispatch.dylib              0x1846f1d30 _dispatch_root_queue_drain
14 libdispatch.dylib              0x1846f1a80 _dispatch_worker_thread3
15 libsystem_pthread.dylib        0x184a17fac _pthread_wqthread
16 libsystem_pthread.dylib        0x184a17b08 start_wqthread

**Comment by FranciscoFortes** [comment]
Hi,
I believe this issue was fixed in the release 1.6.210 from May 10th, can you confirm you have the latest version of the SDK?
