### ISSUE TITLE
Could not make contactless payment

### ISSUE THREAD

**Issue by mpodeszwa** [mposSVK/acceptSDK#4]
Normal payment (putting card into socket and typing PIN) works but when I try to make contactless payment I get `NSError`:

```
Error Domain=Accept Code=9 "30 - Format error." UserInfo={
    NSLocalizedDescription = "30 - Format error.";
}
```

Do I need to make extra steps to enable contactless payment?
Device: Spire SPm2 (firmware v2.30_3D_02111501)
iOS 9.2.1
acceptSDK 1.6.177

**Comment by WirecardMobileServices** [comment]
Contactless support for SPm2 was not officially released yet - pending certification closure - however the latest build #182 has all necessary functions in place.
1. Spire released new firmware for SPm2 that supports Contactless flow - please refer to the Accept Demo application and/or Integration Guide documentation on how to download the firmware to the SPm2 device
2. Make sure the terminal configuration files were downloaded to the SPm2 - again please refer to the Accept Demo or Integration documentation for details on how to perform these tasks

To update the configuration by using Accept Demo app - 
1. Navigate to the Payment tab 
2. Select the paired terminal from the list of terminals e.g. Spire | SPm2-123456789 
3. Once selected the configuration update process starts (please have a look at the implementation and replicate in your application as see fit)

To update the firmware:
1. Navigate to the Payment tab
2. If the proper terminal is selected press the FW Update button which will start the firmware update process

After successful configuration and firmware updates  you should be able to process also contactless payments

**Comment by WirecardMobileServices** [comment]
Contactless card processing certification is all OK, Contacless support enabled in 1.6.189
