### ISSUE TITLE
Spire device not asking for card pin and directly redirects to signature request.

### ISSUE THREAD

**Issue by divyanshyadav** [mposSVK/acceptSDK#5]
When I am doing payment through sipre SPm2, it some times ask for pin and some time does't ask for card pin and directly redirects to signature request.
Why it is not asking for card pin? Is there is any statement I am missing in the implementation?

**Comment by WirecardMobileServices** [comment]
Every card application has the list of verification methods set (CVM list). 
Based on the setup of the terminal (amount threshold for online/offline authentication) and the card CVM the user is prompted for the PIN or Signature or both.

Are you testing always the same card and same amount? Does your card have more than one application (e.g. Visa Debit, Visa Credit) on a chip ?

**Comment by divyanshyadav** [comment]
Ok,  I have tested two different chip visa cards and it always prompt me for the signature validation. Is there is any way to check CVM for the payment or any way to set the CVM for particular card.

**Comment by WirecardMobileServices** [comment]
The CVM is stored on the card chip. At the time of transaction the card will decided which verification method it will use (Signature or PIN)

The behaviour may vary based on the e.g. amount so if you pay 1 EUR the certain card can go for Offline PIN verification, debit card (German) can go for Signature verification only.

If you go above the threshold e.g. 20 EUR then the PIN may be required (no signature)

It really depends on CVM and card application decision process.

You can check the CVM and other EMV data in the response - check the AcceptTransaction object cnpTransactionCertificate attribute - You can use http://www.emvlab.org/tlvutils/ EMV decoder to check the CVM that were used for the transaction

**Comment by divyanshyadav** [comment]
Now I have pay for 50ERU from the same card and again it was prompting for the signature check. By default I am using this method for the call back

-(void)requestSignature:(AcceptSignatureRequest \*  )signatureRequest
{
    UIImage *signatureImage = [UIImage imageNamed:@"signature_sample"];
    signatureRequest.signatureCallback(signatureImage, nil);  
}

8E Cardholder Verification Method (CVM) List
    000000000000000002031E031F00
9F34 Cardholder Verification Method (CVM) Results
    1E0300

What does it mean?

**Comment by WirecardMobileServices** [comment]
The CVM List says it should go for PIN then Signature.
This behaviour was overridden however - I noticed that in our test backend for the SPm2 terminals the terminal capabilities setting was set in a way the card always opted for Signature, I have updated it to the default setting. Can you try it again ?

**Comment by divyanshyadav** [comment]
Thanks, now it's asking for the pin.
