### ISSUE TITLE
Transaction Rejected

### ISSUE THREAD

**Issue by divyanshyadav** [mposSVK/acceptSDK#7]
I frequently getting "Transaction Rejected:250 - system error.(1. Please contact customer service.)" on doing transaction. What is the cause of this error?

**Comment by WirecardMobileServices** [comment]
The integration backend and Payment Engine is connected to our Visa and Mastercard test simulators.
These receive updates, configuration changes etc. overtime and it happens unfortunately that they are down occasionally - in this case  you will get 250 - system error. 

You can try to run your test with different card issuer - so e.g. If you get the failures on Mastercard card then try to use Visa instead please.

**Comment by WirecardMobileServices** [comment]
Temporary disruption of test domain
