### ISSUE TITLE
Could you please explain the cause of this error

### ISSUE THREAD

**Issue by divyanshyadav** [mposSVK/acceptSDK#9]
579 - Transaction processing not possible. (1. Referenced transaction is being processed off-line. and 2. The referenced transaction cannot be cancelled anymore.)

**Comment by WirecardMobileServices** [comment]
You have tried to Cancel/Reverse the transaction that is already submitted for acquiring.
You can inspect "reversible" attribute on the transaction - if reversible=true then you can reverse, otherwise you can only "Refund"

**Comment by divyanshyadav** [comment]
Can we able to refund the transaction from SDK?

**Comment by WirecardMobileServices** [comment]
You can use requestOperationOnPaymentWithID method to perform Reverse | Refund | Send Receipt
Please consult Integration Guide Accept SDK.pdf  section 3.3 Actions on a Payment for details.
For refunds you would pass:
- payment ID
- AcceptOperationOnPaymentRefund
- paymentUpdateParameters (note would be sufficient)
- completion
